### PR TITLE
Feature(Trn 93 create a get method in friends that returns the pending friend requests)

### PR DESCRIPTION
**Pull request by jestebanpelaez18**
I have added a new method in the friends view that returns the pending friend requests of the current user log-in. I will do another Confluence about how to test it in Postman.

### CODE REVIEW

**Review by RushMaverick — APPROVED** [review]
Nice, be sure to be in contact with the frontend about how the fetching from the frontend works! 
Great job!

**Review by Stte — CHANGES_REQUESTED** [review]
Just realized that you can spam same user with multiple friend requests and if you accept one all the rest stays as pending. Can we fix it? Should we fix it?
image

Oh and you can send friend requests to users that have already accepted your request.

**Comment by jestebanpelaez18** [comment]
Ohh true! I will check it, im not checking that when i send the friend request. It might not be difficult.

**Review by jestebanpelaez18 — COMMENTED** [review]
Done it!

**Review by Stte — APPROVED** [review]
LGTM :+1:

**Pull request merged**
