### PR TITLE
chore: add postmant collection jsons

### PR DESCRIPTION
**Pull request by Stte**
Added postman collections to dev/postman_collectons.

### CODE REVIEW

**Review by RushMaverick — COMMENTED** [review]
Was the token issue resolved already?

**Review by jestebanpelaez18 — APPROVED** [review]
approve

**Comment by Stte** [comment]
> Was the token issue resolved already?

Nah the server still crashes when a client tries to connect without Authorization token, but I made an issue out of it so all good :D

**Review by RushMaverick — APPROVED** [review]
Ok, good hustle!

**Pull request merged**
