### PR TITLE
Trn 149 Add search bar for users in the pong game

### PR DESCRIPTION
**Pull request by RushMaverick**
Search bar is now added to the Pong and Tournament modes. It is not connected to the backend so it does nothing currently. 
I also added some styling for the links so they look interactable. 
image

### CODE REVIEW

**Review by ynslee — COMMENTED** [review]
Both one-vs-one.js and tournament.js are missing the part where you send the json file and how you show the result based on the response 😉

**Review by jestebanpelaez18 — APPROVED** [review]
Nice!

**Comment by RushMaverick** [comment]
I removed the search bar since we will be using an alternative method!

**Review by ynslee — APPROVED** [review]

**Comment by ynslee** [comment]
Please fetch and pull before merge! ☺️

**Pull request merged**
