### PR TITLE
Feature(Trn 78 friend feature for users)

### PR DESCRIPTION
**Pull request by jestebanpelaez18**
Friends feature for user working now! You can send a friend request, accept it, and return the list of friends. I have added comments in the functions I created so you can understand what is happening in the code. I will do a document in Confluence where you can see how to test this functionality in POSTMAN.

### CODE REVIEW

**Review by RushMaverick — APPROVED** [review]
Nice, I appreciate the comments for how the methods work.

**Review by ynslee — APPROVED** [review]
Looks great! thank you for the detailed comments! :)

**Review by Stte — APPROVED** [review]
Looking good!

**Comment by jestebanpelaez18** [comment]
Merged, Fetch and Pull

**Pull request merged**
