### PR TITLE
Trn 68 refactor dom for frontend

### PR DESCRIPTION
**Pull request by rosamakinen**
refactoring the DOM for frontend

added a js file for form input fields

Basic Dom functions now can be found from AView including: 
-CreateHeader1
-CreateHeader2
-CreateParagraph
-CreateAnchor
-CreateParagraphWithLink
-CreateForm
-CreateButton

### CODE REVIEW

**Review by RushMaverick — CHANGES_REQUESTED** [review]
CreateHeader1 & 2 can be merged into a single function by taking in an extra element that defines if it is h1 or h2. Can you change that? Otherwise all good!

**Review by RushMaverick — APPROVED** [review]
Nice, beautiful! 
Approved!

**Comment by RushMaverick** [comment]
Did you mean to merge this to TRN-67 and not main? 
If the refactor is done I mean.

**Comment by rosamakinen** [comment]
@RushMaverick yeah, since this has been based off of TRN-67 branch, I think it's better to keep the order and to merge this back to the TRN-67 first and then merge that to main. Or then you can PR and merge the 67 first to main and I can merge 68 to the main after it.

**Comment by RushMaverick** [comment]
Alright, we can do it in a cascading fashion. Let's merge it like this and then merge 67 to main. I'll put up a PR soon!

**Review by jestebanpelaez18 — APPROVED** [review]
Nice! you are doing an amazing !

**Comment by RushMaverick** [comment]
An amazing what? **AN AMAZING WHAT**

**Comment by rosamakinen** [comment]
SPIT IT OUT JUAN! AMAZING WHAT

jk going to merge now, thanks guys

**Pull request merged**
