### PR TITLE
Feature(Trn 98 add online feature in friends app)

### PR DESCRIPTION
**Pull request by jestebanpelaez18**
I have added Online Status to friends app. So whenever you want to see the Friends list from an user, you will see which friends are online or offline. If the user is online you will see the variable is_online = True, if it's offline you will see the variable is_online = False.

I will create a confluence where I'm gonna explain how to test this feature in postman, which uses web sockets. Also, I have added new comments on the new functions.

### CODE REVIEW

**Review by ynslee — APPROVED** [review]
For me it looks good! I will wait for your document to see how I can test it & see what I can do with it on the frontend :)

From my computer, this looks like it hasn't pulled the latest main yet. Could you have a look? :)

**Comment by jestebanpelaez18** [comment]
I will fetch and pull, and push the changes again! I totally forgot it

**Review by RushMaverick — APPROVED** [review]
Nice, good work Juan! 
One step closer. 
Are getters a usual Python thing?

**Comment by jestebanpelaez18** [comment]
At least for this case, we need a getter because we need the online Status from OnlineStatus model, so in that way, we can implement it on the Friends app.

**Pull request merged**
