### PR TITLE
Trn 106 add language selection to settings

### PR DESCRIPTION
**Pull request by rosamakinen**
Created Settings -page where user can change their information on the website.

- changing username, password, and language (from dropdown)
- translations for the page
- delete account -button

_this is not connected to the backend yet, but we transform the data into JSON format_

Screenshot 2024-07-08 at 14 58 44

### CODE REVIEW

**Review by jestebanpelaez18 — APPROVED** [review]
Nice! i really like this feature!

**Comment by ynslee** [comment]
Looks good! For changing the username, would it be easier for backend to change data if we send old username as well or is it easy for them anyhow? or has this been discussed already? :)

**Review by RushMaverick — APPROVED** [review]
Hyvää työtä! 
Code looks clean, but let's look through it once all features are done.

**Comment by rosamakinen** [comment]
> Looks good! For changing the username, would it be easier for backend to change data if we send old username as well or is it easy for them anyhow? or has this been discussed already? :)

Yeah, I was thinking that we should have something to recognize the user as well. I saw someone implementing ID's? is that still a thing? we could use those to keep track of the users, if so. Using the old username to change to new is a valid idea as well.

**Pull request merged**
